site_name: Scrapper Portal da Transparência Docs
plugins: 
  - search
  - glightbox
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            show_source: false
            show_root_full_name: false
            show_signature: true
            show_signature_annotations: true
            show_source_link: true
            show_inheritance: true
            show_inheritance_graph: true
            show_inheritance_diagram: true
            show_inheritance_diagram_depth: 2
            show_inheritance_diagram_options:
              graphviz_dot: dot
    
markdown_extensions: 

  - attr_list
  - admonition
  - def_list
  - footnotes
  - md_in_html
  - tables
  - pymdownx.highlight
  - pymdownx.superfences

  - toc:
      permalink: true
      title: Table of Contents
      separator: '-'
  - codehilite:
      guess_lang: false
      use_pygments: true
    

theme: 
  name: material
  highlightjs: true
  palette:
    scheme: default
    toggle:
      icon: material/toggle-switch
      name: Switch to dark mode
  features:
    - navigation.tabs
    - navigation.top
    - navigation.expand
    - navigation.sections
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.search.highlight
    - navigation.search.suggest
    - navigation.search.share

nav:
  - Home: index.md
  - Crawler:
      - Reference:
          - Portal da Transparência: crawler/portal_transparencia.md
          - Searcher: crawler/searcher.md
          - Details: crawler/details.md
          - Schemas: crawler/schemas.md
          - Filters: crawler/filters.md
          - Elements Selectors: crawler/elements_selectors.md
  - API: https://desafio-mosqti-production.up.railway.app/docs